{% set version = "0.9.1.8" %}
{% set data = load_setup_py_data() %}
package:
  name: rdf_data_citation
  version: "{{ data['version'] }}"

source:
  git_url: "{{ data['url'] }}.git"
  git_rev: master


build:
  linux-64: python
  number: 0


requirements:
  build: 
    - python 3.8
  host: 
    - python 3.8
    - setuptools >=46.1.3
  run:
    {% for req in data['install_requires'] %}
    - {{ req.lower() }}
    {% endfor %}


about:
  home: {{ data['url'] }}
  description: {{ data['long_description'] }}
  license: {{ data['license'] }}
  summary: {{ data['description'] }}

